# -*- coding: utf-8 -*-
"""HW6-GAN

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fRpBXddCkg7WH04VI5dyq9KhGL1zccwQ

# **Homework 6 - Generative Adversarial Network**

This is the example code of homework 6 of the machine learning course by Prof. Hung-yi Lee.


In this homework, you are required to build a generative adversarial  network for anime face generation.

## Set up the environment

### Packages Installation
"""

import torch
 
GPU_name = torch.cuda.get_device_name()
print("Your GPU is {}!".format(GPU_name))

!pip install stylegan2_pytorch

"""### Download the dataset
**Please use the link according to the last digit of your student ID first!**

If all download links fail, please follow [here](https://drive.google.com/drive/folders/13T0Pa_WGgQxNkqZk781qhc5T9-zfh19e).

* To open the file using your browser, use the link below (replace the id first!):
https://drive.google.com/file/d/REPLACE_WITH_ID
* e.g. https://drive.google.com/file/d/1IGrTr308mGAaCKotpkkm8wTKlWs9Jq-p
"""

workspace_dir = '.'
!gdown --id 1WGixTJ1p3pmmE54dRZyZag1Hbx_WC9eG --output "{workspace_dir}/crypko_data.zip"
!unzip -q "{workspace_dir}/crypko_data.zip" -d "{workspace_dir}/"

!stylegan2_pytorch --data /content/faces --num-train-steps 50000

!mkdir -p /content/output

for i in range(16):
  !stylegan2_pytorch  --generate

from PIL import Image
import os
counter = 0
img_name_list = []

def get_name(sourcedir):
	for fname in os.listdir(sourcedir):
		if '-0-ema.jpg' in fname:
			img_name_list.append(fname)
get_name('/content/results/default/')

def crop_save_img(sourcedir):
	img = Image.open(sourcedir)
	w = 128
	h = 128
	x = 0
	y = 0
	global counter
	for i in range(1, 9):
		for j in range(1, 9):
			counter += 1
			x = (i-1)*(w+2)
			y = (j-1)*(h+2)
			temp_img = img.crop((x, y, x+w, y+h))
			image = temp_img.resize((75, 75))
			name = str(counter) + ".jpg"
			if counter <= 1000:
				image.save('/content/output/'+name)
for fname in img_name_list:
	crop_save_img('/content/results/default/'+fname)

# Commented out IPython magic to ensure Python compatibility.
# %cd output
!tar -zcf ../images.tgz *.jpg
# %cd ..

from google.colab.files import download
download("images.tgz")

"""**Ref:https://github.com/lucidrains/stylegan2-pytorch**"""